/* Content for rx5950xt.github.io — edit this file to update the page. */

const LANG_COLOR = {
  'C++': '#f34b7d',
  TypeScript: '#3178c6',
  Python: '#3572A5',
  Rust: '#dea584',
  JavaScript: '#f1e05a',
};

const DATA = {
  handle: 'rx5950xt',

  /* Links on plate: GitHub | Hugging Face | Local.ai | X | Discord */
  links: [
    { label: 'GitHub', url: 'https://github.com/rx5950xt' },
    { label: 'Hugging Face', url: 'https://huggingface.co/RX5950XT' },
    { label: 'Local.ai', url: 'https://local.ai/rx5950xt' },
    { label: 'X', url: 'https://x.com/RX5950XT' },
    { label: 'Discord', url: 'https://discord.com/users/876324357893410817' },
  ],

  /* Plate: machine specs (values with en/zh only when they differ).
     Array value = stacked lines under one key (GPU lists 5060, 3060, then 3070). */
  rig: {
    specs: [
      { key: 'CPU', value: 'AMD Ryzen 7 5700X' },
      { key: 'GPU', value: ['RTX 5060 Ti 16GB', 'RTX 3060 Ti 8GB', 'RTX 3070 Ti FE'] },
      { key: 'RAM', value: 'DDR4 96GB' },
      { key: 'AUD', value: 'Sennheiser HD 550 + FiiO KA13' },
      { key: '3DP', value: 'Bambu Lab A1' },
      { key: 'VR', value: 'Meta Quest 2' },
    ],
  },

  /* Left plate: likes / dislikes, straight under the bio. */
  taste: {
    likes: {
      en: 'Open-source AI · GPUs · VRAM · tokens · dark mode · scrolling the X timeline',
      zh: '開源 AI · GPU · VRAM · token · 深色模式 · 滾動 X 時間軸',
    },
    dislikes: {
      en: 'LINE (the worst messenger ever shipped)',
      zh: 'LINE（有史以來最爛的通訊軟體）',
    },
  },

  /* Left plate bottom: chat sites + one-click install commands. */
  tools: {
    chats: [
      { label: 'Grok', url: 'https://grok.com/' },
      { label: 'Claude', url: 'https://claude.ai' },
      { label: 'ChatGPT', url: 'https://chatgpt.com' },
      { label: 'Gemini', url: 'https://gemini.google.com' },
    ],
    /* Order fixed: Claude Code → Codex → Grok Build → Antigravity.
       Windows-first installers where official; npm for Codex. */
    installs: [
      {
        label: 'Claude Code',
        cmd: 'irm https://claude.ai/install.ps1 | iex',
      },
      {
        label: 'Codex',
        cmd: 'npm install -g @openai/codex',
      },
      {
        label: 'Grok Build',
        cmd: 'irm https://x.ai/cli/install.ps1 | iex',
      },
      {
        label: 'Antigravity CLI',
        cmd: 'irm https://antigravity.google/cli/install.ps1 | iex',
      },
    ],
  },

  ui: {
    en: {
      tagline: 'Vibe coder. Builds everything with agents.',
      bio: 'I build web and Android apps, push big models as fast as they will go on my own GPUs, fine-tune small models of my own, write ESP32 firmware, have AI draw parts for my 3D printer, and backtest investing and the lottery. Most of it grew out of handing a problem to an agent and seeing what came back.',
      localTime: 'Local time',
      demo: 'demo',
      code: 'GitHub',
      themeLabel: 'Switch to the daytime sky',
      themeLabelDark: 'Switch to the night sky',
      dayText: 'Day',
      nightText: 'Night',
      langLabel: '切換為繁體中文',
      footer: '',
      ctxTitle: 'Quick links',
      ctxMenu: 'Site menu',
      chromeLabel: 'Site controls',
      likes: 'Like',
      dislikes: 'Nope',
      linksTitle: 'Links',
      rigTitle: 'Rig',
      rigWish:
        'Urgently seeking a DGX Spark for local deploy, fine-tunes, and development!',
      toolsTitle: 'Use them',
      toolsChats: 'Chat',
      toolsInstalls: 'Install',
      copy: 'Copy',
      copied: 'Copied',
      copyAria: 'Copy install command',
      downloads: 'Downloads',
      topicsLabel: 'Jump to a topic',
      topics: { ai: 'AI', infra: 'AI Infra', models: 'Models', hw: 'Hardware', '3dp': '3D printing', money: 'Money', apps: 'Apps' },
      // {t} is a relative time from the GitHub API ("3 days ago").
      pushed: 'pushed {t}',
    },
    zh: {
      tagline: 'Vibe Coder。用 Agent 建造一切。',
      bio: '做網頁和 Android App，在自己的顯卡上把大模型跑到最快，微調自己的小模型，寫 ESP32 韌體，讓 AI 畫 3D 列印的零件，也拿資料回測投資和樂透。這些大多是把問題丟給 Agent，看它長出什麼來。',
      localTime: '當地時間',
      demo: '試用',
      code: 'GitHub',
      themeLabel: '切換為白天',
      themeLabelDark: '切換為星空',
      dayText: '白天',
      nightText: '星空',
      langLabel: 'Switch to English',
      footer: '',
      ctxTitle: '快捷連結',
      ctxMenu: '網站選單',
      chromeLabel: '網站控制列',
      likes: '喜歡',
      dislikes: '不喜歡',
      linksTitle: '連結',
      rigTitle: '本機配置',
      rigWish: '急需一臺 DGX Spark 用於本地部署、微調與開發！',
      toolsTitle: '使用它們',
      toolsChats: '對話',
      toolsInstalls: '安裝',
      copy: '複製',
      copied: '已複製',
      copyAria: '複製安裝指令',
      downloads: '下載次數',
      topicsLabel: '跳到主題',
      topics: { ai: 'AI', infra: 'AI Infra', models: '模型', hw: '硬體', '3dp': '3D 列印', money: '理財', apps: '應用' },
      pushed: '{t}更新',
    },
  },

  projects: [
    {
      name: 'just-a-submarine',
      repo: 'https://github.com/just-a-submarine',
      demo: 'https://rov-web-xi.vercel.app',
      lang: 'C++',
      topic: 'hw',
      tags: ['ESP32-S3', 'ESP-NOW', 'ROV', 'PlatformIO'],
      en: 'A home-built remote-controlled submarine for an electronics course final, with a 3D-printed hull. Two ESP32-S3 boards talk wirelessly — the sub drives the thrusters, reads the sensors and streams and records video, while the shore station relays commands. Steer it from a phone browser with an Xbox pad, or with on-screen sticks.',
      zh: '電子學課的期末專題，自己做的遙控潛艇，船殼是 3D 列印的。兩塊 ESP32-S3 無線對講：潛艇負責推進、感測、拍影片和錄影，岸上的基地臺負責轉發指令。拿手機瀏覽器接 Xbox 手把就能開，沒手把也有螢幕搖桿。',
    },
    {
      name: 'LLM Wiki',
      repo: 'https://github.com/rx5950xt/LLM-wiki',
      demo: 'https://llm-wiki-seven.vercel.app',
      lang: 'TypeScript',
      topic: 'ai',
      tags: ['Next.js', 'Supabase', 'Google Drive', 'Kotlin'],
      en: 'A wiki that keeps itself organised. Drop in a link or a document and an LLM writes it into linked notes — one source usually touches ten or more pages, and it flags where two sources disagree. Everything is plain Markdown in your own Google Drive, on the web and on Android.',
      zh: '會自己整理的 wiki。丟進網址或文件，LLM 會把它寫進互相連結的筆記：一份資料通常會改到十幾頁，兩份資料說法打架也會標出來。檔案都是 Markdown，放在你自己的 Google Drive，有網頁版和 Android 版。',
    },
    {
      name: 'Portfolio Visualizer',
      repo: 'https://github.com/rx5950xt/portfolio-visualizer',
      demo: 'https://portfolio-visualizer-roan.vercel.app/',
      lang: 'TypeScript',
      topic: 'money',
      tags: ['Next.js', 'TWR / XIRR', 'ETF look-through', 'RBAC'],
      en: 'A holdings dashboard for long-term investors, Taiwan and US stocks alike. It works out your real return and worst drop, opens up ETFs to show what you actually own, and replays the same buys into the S&P 500 for comparison. An AI check-up flags over-concentration, ETF overlap and fees. Log in with "demo" to get a sandbox of your own.',
      zh: '給長期投資的人用的持股儀表板，台股美股都能放。算出真實報酬和最大跌幅，拆開 ETF 看你實際持有哪些公司，再把同樣的買點換成 S&P 500 比一比。AI 健診會指出押太集中、ETF 重疊和費用。密碼輸入 demo 就有一個自己的試玩空間。',
    },
    {
      name: 'VoiceInk',
      repo: 'https://github.com/RX5950XT/VoiceInk',
      lang: 'JavaScript',
      topic: 'ai',
      tags: ['Electron', 'Rust sidecars', 'llama.cpp', 'sherpa-onnx'],
      en: 'An AI workbench for Windows that keeps the daily tools in one app: chat with any model, run several Claude Code or Codex terminals side by side, pull models from Hugging Face and run them locally, and see the quota left on seven subscriptions. Hold right Alt in any app to dictate — speech recognition can run fully offline.',
      zh: 'Windows 上的 AI 工作台，每天用的東西收在同一個 App：跟各家模型聊天、同時開好幾個 Claude Code／Codex 終端機、從 Hugging Face 抓模型在本機跑、看七家訂閱還剩多少額度。在任何程式按住右 Alt 就能用講的打字，語音辨識可以完全離線。',
    },
    {
      name: 'ESP32-CAM Remote Monitor',
      repo: 'https://github.com/rx5950xt/ESP-32-CAM_remote_monitor',
      lang: 'C++',
      topic: 'hw',
      tags: ['ESP32-CAM', 'PlatformIO', 'Telegram Bot', 'TinyML'],
      en: 'An ESP32-CAM that watches a room over Telegram: ask for a photo or one every few seconds, and with person detection on, it sends you a shot as soon as someone walks in. Spotting people runs on the tiny board itself — no cloud, no API key — and the exposure is tuned for low light.',
      zh: '用 ESP32-CAM 顧房間，全靠 Telegram 操作：傳指令就拍照，也能每隔幾秒回傳一張；開了人物偵測，看到有人就自動傳照片給你。認人在小小的板子上就做完，不用雲端也不用 API 金鑰，光線暗也調過曝光。',
    },
    {
      name: 'LLM Arena',
      repo: 'https://github.com/rx5950xt/LLM-Arena',
      demo: 'https://llm-arena-opal.vercel.app',
      lang: 'TypeScript',
      topic: 'ai',
      tags: ['OpenRouter', 'Streaming', 'LLM-as-judge', 'Provider compare'],
      en: 'Ask up to fifteen models the same question, watch the answers stream side by side, and let a judge model score them. It can also race one model across providers to see who is cheaper or faster, or set two models debating for up to ten rounds, scored by four judges and saved as a PDF. Runs in your browser; your key never leaves it.',
      zh: '同一個問題一次問最多 15 個模型，答案並排跑出來，再請裁判模型打分。也能比同一個模型在哪家供應商比較便宜、比較快，或讓兩個模型辯論最多十回合，四位裁判評完還能存成 PDF。全部在瀏覽器裡跑，金鑰不會離開你的電腦。',
    },
    {
      name: 'Qwen3.8-27B × Two Mismatched GPUs',
      repo: 'https://github.com/RX5950XT/Qwen-3.8-27B-DualGPUs',
      lang: 'Python',
      topic: 'infra',
      tags: ['llama.cpp', 'MTP', '256K context', 'OpenAI · Anthropic API'],
      en: 'A 27B model split across a 16GB and an 8GB card that were never meant to pair — up to about 200K tokens of context at 28–35 tokens per second, and it reads images too. Double-click and it sets itself up, and a control panel downloads a model with one click and serves an API that speaks both OpenAI and Anthropic.',
      zh: '把 27B 模型拆到一張 16GB、一張 8GB 兩張不成對的顯卡上，一次最多讀約 20 萬 token，每秒 28–35 個 token，也看得懂圖。雙擊就自己裝好，控制面板點一下就下載模型、上線，開出 OpenAI 和 Anthropic 格式都能接的 API。',
    },
    {
      name: 'Qwen-35B-A3B × RTX 3070 Ti',
      repo: 'https://github.com/rx5950xt/Qwen-35BA3B-RTX3070Ti',
      lang: 'Python',
      topic: 'infra',
      tags: ['llama.cpp', 'MoE', 'Quantization', '8GB VRAM'],
      en: 'A 35B model squeezed onto one 8GB card. This kind of model only wakes a small slice of itself for each word, so the GPU and CPU can share the work; an automated sweep then found the fastest settings — 35 tokens per second. It also measured what dual-channel memory buys over single: about 20%.',
      zh: '把 35B 模型塞進一張 8GB 顯卡。這種模型每次只叫醒一小部分，所以能讓顯卡和 CPU 分工；再用自動測試找出最快的設定，實測每秒 35 個 token。也量了記憶體從單通道換成雙通道能快多少：約兩成。',
    },
    {
      name: 'PCPriceProxy',
      repo: 'https://github.com/rx5950xt/PCPriceProxy',
      lang: 'TypeScript',
      topic: 'money',
      tags: ['Scraping', 'SKU matching', 'REST API', 'Agent CLI'],
      en: 'Compare PC part prices across CoolPC, Sinya and Autobuy in one go. The same model becomes one card with all three prices side by side — it would rather keep two listings apart than merge the wrong ones — and prices refresh every 30 minutes. Parts are sorted the way you shop, like motherboards by socket and chipset. An API and a command-line tool let an AI do the shopping.',
      zh: '一次比完原價屋、欣亞、Autobuy 的電腦零件價。同一型號併成一張卡，三家價格擺在一起；寧可分開也不亂併，每 30 分鐘自動更新。零件照買的時候會看的規格分類，像主機板能照腳位、晶片組一路篩。也有 API 和指令列工具，讓 AI 幫你比價。',
    },
    {
      name: '0050 Buy-Point Study',
      repo: 'https://github.com/rx5950xt/Buy_Price_Assessment',
      lang: 'Python',
      topic: 'money',
      tags: ['Walk-forward', 'Bootstrap CI', 'Sealed holdout', '0050 · VT'],
      en: 'If you buy 0050 once a month, which day is best? Twenty-three years of data say nearly half of each month’s lows land in the first five trading days, so the steadiest move is to buy at the open on day one — the machine-learning strategy trained to beat it paid more. Rerun on VT, the global stock ETF, the answer holds.',
      zh: '每個月買一次 0050，哪一天買最好？拿 23 年資料回測，每月最低價有將近一半落在前 5 個交易日，最穩的做法就是第一個交易日開盤直接買；特地訓練來打敗它的機器學習策略反而買得更貴。換成全球股票 ETF VT 重跑，結論一樣。',
    },
    {
      name: 'Taiwan Lottery Study',
      repo: 'https://github.com/RX5950XT/Taiwan_Lottery',
      lang: 'Python',
      topic: 'money',
      tags: ['4,000+ draws', 'Expected value', 'Sports betting', 'Playbook'],
      en: 'Can you play the lottery smarter? Over 4,000 draws are pure chance — hot numbers, cold numbers and machine learning all tie with random picks, and every NT$100 on Lotto 6/49 returns NT$50 on average. Only two things help: pick unpopular numbers so you split less if you win, and play only when the jackpot is big enough, which happened sixteen times in eighteen years.',
      zh: '樂透能不能買得比較聰明？4,000 多期開獎證實號碼完全隨機，熱門號、冷門號、機器學習都贏不了亂選；大樂透每花 100 元平均只拿回 50 元。能改的只有兩件事：選冷門號，中了少跟人分；等頭獎夠高再買——18 年來只有 16 期划算。',
    },
    {
      name: '3DP-MATX',
      repo: 'https://github.com/RX5950XT/3DP-MATX',
      lang: 'Python',
      topic: '3dp',
      tags: ['FreeCAD CSG', 'Parametric', 'PETG', 'Bambu Lab A1'],
      en: 'A fully 3D-printed microATX NAS case for four 3.5-inch drives. Every dimension is computed in code, then AI drives FreeCAD to build it and checks it against the spec line by line. Twenty-four printed pieces, 13.8 litres; the shell locks together with slide rails and snap catches, and even the motherboard screws are printed.',
      zh: '全 3D 列印的 microATX NAS 機殼，裝得下 4 顆 3.5 吋硬碟。每個尺寸都用程式算出來，再讓 AI 操作 FreeCAD 建模、逐條對照規格驗證。共 24 個列印件、13.8 公升；外殼靠滑槽和卡榫扣在一起，連鎖主機板的螺絲都是印的。',
    },
  ],

  more: [
    {
      name: 'calcrux',
      repo: 'https://github.com/rx5950xt/calcrux',
      lang: 'Rust',
      topic: 'apps',
      en: 'An Android calculator with a Rust core that keeps exact fractions — it also converts units, works out loans and checks exchange rates',
      zh: '核心用 Rust 寫的 Android 計算機，分數算到底都不失真，還會換單位、算貸款、查匯率',
    },
    {
      name: 'FJU-TronClass-MCP',
      repo: 'https://github.com/RX5950XT/FJU-TronClass-MCP',
      lang: 'Python',
      topic: 'apps',
      en: "Lets an AI run FJU's TronClass for you — check courses and to-dos, download a whole semester of materials, mark videos as watched",
      zh: '讓 AI 幫你操作輔大 TronClass：查課程和待辦、整學期教材一次下載、把影片標成看完',
    },
    {
      name: 'rolling-around',
      repo: 'https://github.com/rx5950xt/rolling-around',
      demo: 'https://katamari-web-game.onrender.com/',
      lang: 'TypeScript',
      topic: 'apps',
      en: 'A 3D browser game: roll a ball and swallow the world, from flowers up to skyscrapers, through day, night and rain',
      zh: '瀏覽器裡的 3D 小遊戲：滾著球把世界吞掉，從花草一路吃到大樓，還有日夜和下雨',
    },
    {
      name: 'surface_optimizer',
      repo: 'https://github.com/RX5950XT/surface_optimizer',
      lang: 'C++',
      topic: 'apps',
      en: 'Makes a Surface Pro 7 last longer and feel snappier — boosts the app in front, slows the background and reins in runaway apps, in 8MB of memory',
      zh: '讓 Surface Pro 7 更省電也更順：眼前的程式立刻加速、背景程式降速、壓住失控的程式，常駐只吃 8MB',
    },
    {
      name: 'AgentCAD_MCP',
      repo: 'https://github.com/RX5950XT/AgentCAD_MCP',
      lang: 'Python',
      topic: '3dp',
      en: 'Lets an AI model in FreeCAD through 22 tools — building, measuring, checking parts for clashes — while you only look and measure',
      zh: '讓 AI 用 22 個工具直接在 FreeCAD 裡建模、量尺寸、查零件有沒有卡到，人只負責看和量',
    },
    {
      name: 'FreeCAD',
      repo: 'https://github.com/RX5950XT/FreeCAD',
      lang: 'C++',
      topic: '3dp',
      en: "AgentCAD's companion — FreeCAD in Traditional Chinese with a dark theme, trimmed down to viewing and measuring, with a Windows installer",
      zh: 'AgentCAD 的配套：FreeCAD 全面繁中化、換上深色介面，精簡到只剩看模型、量尺寸，有 Windows 安裝檔',
    },
    {
      name: '3DP-TV-SpeakerHanger',
      repo: 'https://github.com/RX5950XT/3DP-TV-SpeakerHanger',
      lang: 'Python',
      topic: '3dp',
      en: 'A speaker basket for a TV wall mount — its hooks are only 4mm thick, thin enough for the 8.6mm gap behind the TV. No drilling, no glue',
      zh: '掛在電視壁掛架上的喇叭籃：掛鉤只有 4mm 厚，塞得進電視背後 8.6mm 的縫，不用鑽孔也不用黏',
    },
    {
      name: '3dp-bedside-table',
      repo: 'https://github.com/RX5950XT/3dp-bedside-table',
      lang: 'Python',
      topic: '3dp',
      en: 'A bedside shelf that clips onto the bed board, printed in one piece — no screws, nothing to assemble',
      zh: '直接夾在床板上的床邊置物架，整件一次印完，不用螺絲也不用組裝',
    },
    {
      name: 'Token-Anxiety-Dashboard',
      repo: 'https://github.com/RX5950XT/Token-Anxiety-Dashboard',
      lang: 'Rust',
      topic: 'ai',
      en: 'A desktop gauge showing how much quota Claude Code, Codex, Antigravity, OpenCode and Grok have left, and when each resets',
      zh: '桌面小儀表，一眼看完 Claude Code、Codex、Antigravity、OpenCode、Grok 還剩多少額度、多久後重置',
    },
    {
      name: 'Strata',
      repo: 'https://github.com/RX5950XT/Strata',
      lang: 'C++',
      topic: 'infra',
      en: 'A fork of Strata, which runs a 125B model on one gaming GPU — I added a control panel and let a second GPU hold part of the model',
      zh: 'Strata 的 fork：在一張遊戲顯卡上跑 125B 大模型；我加上控制面板，並讓第二張顯卡幫忙放一部分模型',
    },
    {
      name: 'Laguna-S2.1',
      repo: 'https://github.com/RX5950XT/Laguna-S2.1-RTX5060Ti-RTX3060',
      lang: 'Python',
      topic: 'infra',
      en: 'Laguna S 2.1 on two home GPUs with a 256K context — patched llama.cpp to lift it from 7.2 to 19.3 tokens per second (archived)',
      zh: '在兩張家用顯卡上跑 Laguna S 2.1、開滿 26 萬 token 上下文，改 llama.cpp 讓速度從每秒 7.2 提升到 19.3 個 token（已封存）',
    },
  ],

  models: [
    {
      name: 'silicon-based-girlfriend-v2',
      links: [
        {
          label: 'GGUF',
          url: 'https://huggingface.co/RX5950XT/silicon-based-girlfriend-v2-GGUF',
          icon: 'Hugging Face',
        },
        {
          label: 'LoRA',
          url: 'https://huggingface.co/RX5950XT/silicon-based-girlfriend-v2',
          icon: 'Hugging Face',
        },
        {
          label: 'Dataset',
          url: 'https://huggingface.co/datasets/RX5950XT/silicon-based-girlfriend-v2-dataset',
          icon: 'Hugging Face',
        },
      ],
      downloads: 617,
      tags: ['Qwen3.5-9B', 'SFT + GRPO', 'GGUF'],
      en: 'A second-generation roleplay model for Traditional Chinese, 9B. Plain fine-tuning taught it to talk but wrecked long conversations, so two rounds of reinforcement learning won them back — it stays in character and no longer copies its own earlier lines. Comes as a GGUF ready for Ollama, a LoRA to keep training, and the 2,109 training conversations.',
      zh: '第二代繁中角色扮演模型，9B。先用對話教它說話，長對話卻因此變亂，再用兩輪強化學習救回來：更守人設，也不再抄自己前面講過的話。附 Ollama 直接能用的 GGUF、能接著訓練的 LoRA，以及 2,109 筆訓練對話。',
    },
    {
      name: 'silicon-based-girlfriend',
      links: [
        {
          label: 'Hugging Face',
          url: 'https://huggingface.co/RX5950XT/silicon-based-girlfriend',
          icon: 'Hugging Face',
        },
        {
          label: 'Dataset',
          url: 'https://huggingface.co/datasets/RX5950XT/silicon-girlfriend-dataset',
          icon: 'Hugging Face',
        },
      ],
      downloads: 1628,
      tags: ['Qwen3.5-4B', 'QLoRA r=32', 'GGUF'],
      en: 'The first-generation roleplay model for Traditional Chinese, 4B, trained on 985 conversations for about nineteen hours on an A6000. Comes as a LoRA and a ready-to-run GGUF, and the training conversations are public too.',
      zh: '第一代繁中角色扮演模型，4B，用 985 筆對話在 A6000 上訓練了約 19 小時。有 LoRA 和能直接跑的 GGUF 兩種，訓練對話也一起公開。',
    },
    {
      name: 'rx5950xt-digital-twin',
      url: 'https://huggingface.co/RX5950XT/rx5950xt-digital-twin-Qwen3.5-4B',
      downloads: 123,
      tags: ['Qwen3.5-4B', 'QLoRA r=8', 'zh-TW'],
      en: 'A digital twin of me, trained on about 1,067 of my own Discord messages. Trained lightly on purpose and mixed with twice as much general Chinese data, so it picks up how I talk instead of memorising what I said.',
      zh: '用我自己約 1,067 則 Discord 訊息訓練出來的數位分身。刻意訓練得很輕，還摻了兩倍量的一般中文資料，讓它學會我說話的語氣，而不是背下我說過的話。',
    },
    {
      name: 'LinguaForge-Qwen3.5-0.8B',
      url: 'https://huggingface.co/RX5950XT/LinguaForge-Qwen3.5-0.8B-zhTW-en-ja',
      repo: 'https://github.com/RX5950XT/LinguaForge-Qwen3.5-0.8B-zhTW-en-ja',
      downloads: 388,
      tags: ['Qwen3.5-0.8B', 'LoRA r=64', 'zh-TW · en · ja'],
      en: 'A tiny translator between Traditional Chinese (Taiwan), English and Japanese, in all six directions. The original slipped Simplified characters into over 40% of its Japanese-to-Chinese sentences; after training that is under 1%, and its translation-quality score rose 1.92 points.',
      zh: '繁體中文（臺灣）、英文、日文互翻的小模型，六個方向都能翻。原版日翻中有四成多的句子混進簡體字，訓練後降到不到 1%；翻譯品質分數也提升 1.92 分。',
    },
  ],
};
